### ISSUE TITLE
Creating a class to remove default Tailwinds margins and padding on specific MDX components

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#100]
We're using the Tailwinds Typopgraphy plugin, which nicely styles our articles with readable typography: https://github.com/tailwindlabs/tailwindcss-typography

I've been experimenting with styling Tailwinds + MDX components on this 'Sales Safari in a Nutshell' article: https://github.com/eggheadio/egghead-next/blob/ma/sales-safari-article/src/pages/learn/30x500/sales-safari/index.mdx

At the moment, any Tailwinds classes applied to an MDX / React component are overridden by the Tailwinds typography plugin.

For example, a card component like this with an h3 header has a ton of top margin on it that I can't get rid of:

![image](https://user-images.githubusercontent.com/5599295/94118791-e700a880-fe45-11ea-905e-6b09dbef05a7.png)

The prose CSS declarations override any we define in the original React component. This is the top-level declaration being applied:

```
@media (min-width: 768px)
.md\:prose-xl h3 {
    font-size: 1.5em;
    margin-top: 1.6em;
    margin-bottom: 0.6666667em;
    line-height: 1.3333333;
```

I'm trying to define the styles in this component: https://github.com/eggheadio/egghead-next/blob/0fc88b0612da95be02ed8dccd04b5b2121ab8fb8/src/components/mdx/HeaderCard.js#L3-L12

Adding `m-0` to the component itself, or the h3 specifically doesn't remove the extra margins. The Tailwinds typography plugin still over rides both.

## What I've tried

I want to create a "prose-reset" class we can pop onto text elements in MDX that we want to reset the margins and padding on. Then we can redeclare the margin and padding for each context.

I tried creating a specific class in the tailwinds config: https://github.com/eggheadio/egghead-next/blob/0fc88b0612da95be02ed8dccd04b5b2121ab8fb8/tailwind.config.js#L24-L32

I tried adding a specific class in the index.css: https://github.com/eggheadio/egghead-next/blob/0fc88b0612da95be02ed8dccd04b5b2121ab8fb8/src/styles/index.css#L37-L42

Neither worked so far.

@vojtaholik Any ideas on how to have the MDX components play nicely with Tailwinds typography?
Want to be able to have whatever tailwinds classes we define in an MDX component override the prose defaults.

**Comment by vojtaholik** [comment]
Apart of a reset class, you could apply `prose` classes on individual section level in given MDX file instead of top level in a layout. `<section className=“prose”>` Might make sense in case of an "ultimate guide"?

The reset class would need to be defined in styles/index.css instead of tailwind config. This should work:

```
#__next {
  @apply flex flex-col min-h-screen;
  .prose-reset {
    * {
      @apply m-0 p-0;
    }
  }
}
```

**Comment by MaggieAppleton** [comment]
🙏🙏🙏 The second approach worked perfectly and probably better.

It's fine for most of the article content to have the prose styling applied, and then just for specific elements like callouts, cards, and links we can apply the prose-reset style.

Thank you!

**Comment by MaggieAppleton** [comment]
Tailwind-typography prose is kind of driving me up the wall.

Feels pretty complicated just to figure out how to change the font size, line height, or margin on a piece of text. Having the same problem on the Just JS with the same configuration right now.

Let's say I want to make the line-height on an H1 headline like this 1.4em. How? Adding it to the index.css file, the tailwinds-config.js file, or the React component directly all fail 🤔

![image](https://user-images.githubusercontent.com/5599295/94272865-94091d00-ff3b-11ea-8a9c-d35610d97382.png)

Can't figure out how to control .prose declarations in one central place.

I added the reset class from above to egghead-next, this one:
`#__next {
  .prose-reset {
    * {
      @apply m-0 p-0;
    }
  }
}`

Which removes all margin and padding, but then won't let me add margin and padding back onto elements. The m-0 and p-0 values are overriding everything.
﻿
Can we simplify this somehow?
Any chance I can just write the CSS for our sites in a single location?
Or at least have inline tailwinds classNames in components be the final applied style?
﻿

**Comment by joelhooks** [comment]
Prose is great defaults but notorious for custom from my understanding. I’ve seen loads of complaints.

**Comment by MaggieAppleton** [comment]
@vojtaholik 's first solution worked great.

Made a template called "fancy-guide" and a component called <ProseSection> that applies the prose styles just to specific bits of an MDX file. 

All back on track now.
