### ISSUE TITLE
[BUG] 504 error

### ISSUE THREAD

**Issue by TarunavBA** [eggheadio/egghead-next#1014]
When I open https://egghead.io/ I see this error:

```
This Edge Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: EDGE_FUNCTION_INVOCATION_TIMEOUT
ID: bom1::r4trt-1638939065616-48619b225abb

If you are a visitor, contact the website owner or try again later.
If you are the owner, learn how to fix the error and check the logs.
```

**Comment by joelhooks** [comment]
Reading the edge function documentation they are required to return a response within 1.5 seconds 

https://github.com/eggheadio/egghead-next/commit/24a6e4591dcebbdf912ab1c727fc95397e8ea8e5

In this commit, I've lowered the "safety fallback" to 1.25 seconds, which should be under the timeout threshold if the call to the service provider is slow.

What region are you in @TarunavBA? Can you test this for me and see if it works now?

**Comment by TarunavBA** [comment]
@joelhooks I am in india.

**Comment by TarunavBA** [comment]
@joelhooks now it is resolved thank you.
