### ISSUE TITLE
Please 'pause' at end of video

### ISSUE THREAD

**Issue by tomByrer** [eggheadio/egghead-next#104]
I'd prefer the video to either pause with the full last frame showing, or give an extra 3 seconds at the end of the video to allow manual pausing, vs the current covering of the video at end:
![image](https://user-images.githubusercontent.com/1308419/94340508-00316280-ffc8-11ea-83c6-6bb573f41f9d.png)

When programming along with the video, sometimes I like to type from the video player manually rather than just copy/paste from transcript or GitHub repo.  But when the video ends, I am forced to replay & scrub the timeline indicator to the end paused to see the last few frames again.  [This video ](https://next.egghead.io/lessons/xstate-how-action-order-affects-assigns-to-context-in-a-xstate-machine)is a perfect example; we have only 4 seconds to see the results until the 'play next video' overlay covers it.

Thanks for all your great work!

**Comment by joelhooks** [comment]
@DrShpongle @vojtaholik design-wise an option here might be to shrink the playback window and display this card on the righthand side.

![image](https://user-images.githubusercontent.com/86834/95663905-f8111100-0af7-11eb-9190-8c10316663d6.png)

**Comment by tomByrer** [comment]
Replay button on bottom is a good idea, but what happens if the user wants to scrub the timeline?

**Comment by joelhooks** [comment]
@tomByrer we are looking at this and other issue with the cards currently. i'm closing the issue because we aren't prioritizing this specific problem right now, but it is valid and we are going to consider it when we apply design to this page. 

thanks so much for the feedback 🙏🏼
