### ISSUE TITLE
RFC: Cypress patterns for egghead-next

### ISSUE THREAD

**Issue by dealingwith** [eggheadio/egghead-next#112]
@lsminter and I both wanted to get our hands dirty with egghead-next, so we started with Cypress. I find tests the best way for me to get familiar with a codebase. Once we got past the [new bug in Cypress](https://github.com/cypress-io/cypress/issues/8634) by reverting Cypress to v4.12.1, we learned how to write a test and added one to `spec.js` that asserts a minimum number of menu list items (just as a learning exercise, I'm not sure this is a useful test).

[dm/learning-cypress diff](https://github.com/eggheadio/egghead-next/compare/dm/learning-cypress)

```javascript
it('homepage contains nav', () => {
  cy.visit('/')
  cy.get('nav > ul > li').should(($li) => {
    // currently [Topics] [Search]
    expect($li).length.to.be.at.least(2)
  })
})
```

Because there are not a lot of Cypress tests already (3), there isn't a great way to know how to organize tests, or what areas of the UI would most benefit from tests (besides "[all of them](https://memegenerator.net/img/instances/42953003/test-all-the-things.jpg)"). The purpose of this issue is to discuss what we would like to do IRT both of those topics. I've historically found frontend test methodology to be a contentious topic and would like to defer to the more senior devs here.

I've written tests in Rspec, Cabybara, and Jasmine, but never for a component-based application, so I'm also interested in anyone's go-to docs/articles for how to do this.

Cypress version revert in `package.json` required for tests to run:
```diff
- "cypress": "^5.1.0",
+ "cypress": "^4.12.1",
```
...did not commit this change, obvs

**Comment by joelhooks** [comment]
My testing philosophy is that certain aspects of the application deserve more testing consideration than others and there is diminishing returns relatively quickly in approaches like cypress while having large amounts of value early in. 

https://testingjavascript.com is full spectrum around the mechanics of how this app is set up to test.

**Comment by joelhooks** [comment]
sounds like we've had some progress and resolution on this in other channels so gonna close this issue
