### ISSUE TITLE
Add a possibility to "limited free time"

### ISSUE THREAD

**Issue by YonatanKra** [eggheadio/egghead-next#163]
In the current interface, we can choose between "free" and "pro".
Sometimes, we'd like to run a "promo" - "free for a limited time" or something like that.
A use case I was thinking about is if a topic is hot, I'd setup the "hottest" video in a course as "free for a week" and promote it via social networks.  After one week, the video is automatically set to "pro" again, but allowed for a week of promotion.

**Comment by joelhooks** [comment]
Hey, thanks for the suggestion! I'm going to close it because we won't be able to address it anytime in the near future, but will be reviewing the closed issues later.
