### ISSUE TITLE
New redirect configs are overriding existing next.egghead.io pages

### ISSUE THREAD

**Issue by lsminter** [eggheadio/egghead-next#171]
This [PR](https://github.com/eggheadio/egghead-next/pull/161) added redirects but it appears that it is being too aggressive and redirecting from existing pages to legacy pages on app.egghead.io. For example, navigating to https://next.egghead.io/courses/record-badass-screencasts-for-egghead-io through next.egghead.io (eg. from the search) does not redirect but pasting the link into the browser redirects.

**Comment by joelhooks** [comment]
looks like this was fixed!
