### ISSUE TITLE
Wrong link on "Start watching" button

### ISSUE THREAD

**Issue by CroModder** [eggheadio/egghead-next#206]
On article https://next.egghead.io/playlists/composing-closures-and-callbacks-in-javascript-1223 , "Start watching" href leads to https://next.egghead.io/lessons/undefined

**Comment by joelhooks** [comment]
thanks @CroModder 

This page would render at all for me because of a related issue which is fixed by:

https://github.com/eggheadio/egghead-next/commit/aff31faeebf1b31ac2bfbbbe90b86de95c6e9f0e

It's also not showing any content because this is a "playlist of playlists" and those are not presented!
