### ISSUE TITLE
An unexpected error has occured - while watching video

### ISSUE THREAD

**Issue by kparol-proacta** [eggheadio/egghead-next#210]
Not really sure if this bug is for this repository, but it's for Egghead.io new interface ;)

I was watching video when without any interaction i got this error.
I attach screenshot with console error.
![image](https://user-images.githubusercontent.com/21333792/102185833-f7a74480-3eb1-11eb-911a-f01c7532b587.png)

**Comment by DrShpongle** [comment]
Thanks for letting us know. May you provide the link to that lesson please?

**Comment by kparol-proacta** [comment]
https://next.egghead.io/lessons/wordpress-explore-pages-tags-and-taxonomies-in-the-wordpress-json-route?pl=headless-wordpress-4a14
