### ISSUE TITLE
More audio speed multipliers

### ISSUE THREAD

**Issue by stleport** [eggheadio/egghead-next#243]
Some instructors speak fast, they can be difficult to follow for non native english speakers. 
It would be nice if your can add a multiplier to slow down audio speed between `normal`(too fast) and `.5x`(too slow)  (e.g. `.75x`? `.80x`?) as in the current site.

<img width="241" alt="Capture d’écran 2020-12-29 à 09 51 39" src="https://user-images.githubusercontent.com/45454726/103272533-64940180-49bd-11eb-8532-5b7bf0f79632.png">

**Comment by joelhooks** [comment]
unfortunately this is baked into the Bitmovin player. We’ve filed a request to make this customizable. 

previously we had an external control which worked OK and might be something we co wider again.
