### ISSUE TITLE
Unable to play member exclusive lesson

### ISSUE THREAD

**Issue by mrkldshv** [eggheadio/egghead-next#247]
Hi guys! I have egghead subscription. I've watched about 2-3 lessons and after trying to play next one I got following error. Just wanted to let you know about this type of bug.
![Screen Shot 2020-12-29 at 23 44 07](https://user-images.githubusercontent.com/47859603/103318769-c1c89b00-4a2f-11eb-9ce8-c34b74e8a1f2.png)

**Comment by joelhooks** [comment]
Hey, you can email support@egghead.io and we can help you. Very difficult you help here.

**Comment by mrkldshv** [comment]
Yep, sure. Just to give you a little more context: after trying logging in with cleared cache and cookies fixed the problem. The issue was more for the purpose of you being aware this is happening, just to help out the whole project :)

**Comment by joelhooks** [comment]
thanks! glad you got it working and appreciate the heads up
