### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [eggheadio/egghead-next#300]
## Description 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/egghead-next/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point of time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Unused Expression found [here](https://deepsource.io/gh/HarshCasper/egghead-next/issue/JS-0093/)
- Usage of unsafe target=’_blank’ [here](https://deepsource.io/gh/HarshCasper/egghead-next/issue/JS-0422/occurrences/)
- No unique title in `<iframe>` [here](https://deepsource.io/gh/HarshCasper/egghead-next/issue/JS-0749/)
- Redeclared Variables [here](https://deepsource.io/gh/HarshCasper/egghead-next/issue/JS-0085/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

**Comment by joelhooks** [comment]
thanks we will take a look.
