### ISSUE TITLE
"Logout" CTA seen in normal state (footer)

### ISSUE THREAD

**Issue by farhanhalai30** [eggheadio/egghead-next#301]
Logout CTA is seen, even when the user is not logged-in.

![image](https://user-images.githubusercontent.com/25427496/104930628-67d24a00-59cb-11eb-8dd9-0f58e7e3f750.png)

**Comment by joelhooks** [comment]
thanks, this isn’t an issue and doesn’t cause any harm if clicked repeatedly regardless of authentication state
