### ISSUE TITLE
Podcast pages are missing SEO data

### ISSUE THREAD

**Issue by arthurdenner** [eggheadio/egghead-next#360]
Currently, `/podcasts/[slug]` pages are missing custom SEO data: title, description, etc.

You can find an example of the current status [in this link](https://www.opengraph.xyz/url/https:%2F%2Fegghead.io%2Fpodcasts%2Fshawn-wang-talks-about-how-to-grow-your-reputation-as-a-developer/).

**Comment by joelhooks** [comment]
thanks @arthurdenner 👍
