### ISSUE TITLE
Dereference once

### ISSUE THREAD

**Issue by s4l4x** [eggheadio/egghead-next#40]
Why not dereference all at once?
parent: {child0, child1, ...}

And avoid the two stages? Perhaps it’s a style issue?

https://github.com/eggheadio/egghead-next/blob/ff184c09e66a66f4b7a9ed0f7aae649962408dc5/src/layouts/index.tsx#L18

**Comment by imsamuel** [comment]
> Why not dereference all at once?
> parent: {child0, child1, ...}
> 
> And avoid the two stages? Perhaps it’s a style issue?
> 
> https://github.com/eggheadio/egghead-next/blob/ff184c09e66a66f4b7a9ed0f7aae649962408dc5/src/layouts/index.tsx#L18

They can't be destructured all at once, `frontMatter` is from `props` and the rest is from `frontMatter`.

**Comment by joelhooks** [comment]
layered destructuring is always kind of hard for me to read as well, which is why I don't default to that even when it is possible.
