### ISSUE TITLE
The page is horizontally scrollable

### ISSUE THREAD

**Issue by Beraliv** [eggheadio/egghead-next#522]
Link – https://egghead.io/talks/javascript-master-the-javascript-interview

Probable CSS blame:
<img width="871" alt="Screenshot 2021-03-29 at 22 45 32" src="https://user-images.githubusercontent.com/2991847/112897904-dbd65000-90e8-11eb-8d89-50a87b157484.png">

In code:

https://github.com/eggheadio/egghead-next/blob/main/src/pages/talks/%5Bslug%5D.tsx#L139

After commenting it's fixed for me, but probably used in other cases

Is it expected?

**Comment by Beraliv** [comment]
I created PR for the fix here – https://github.com/eggheadio/egghead-next/pull/523

**Comment by vojtaholik** [comment]
thanks @Beraliv, this has been fixed via https://github.com/eggheadio/egghead-next/pull/525
