### ISSUE TITLE
'Concurrent React from Scratch' talk card on homepage linking to wrong page

### ISSUE THREAD

**Issue by jimpala** [eggheadio/egghead-next#599]
https://github.com/eggheadio/egghead-next/blob/f691468877e4af81fec54d090288c835a4a461ee/src/components/pages/home/homepage-data.ts#L43-L60

51 is the offending line - it appears to be pointing to the CSS grid course.

Free annual subscription pls x

(thanks for the ace content!)

**Comment by laurosilvacom** [comment]
Hey James! This is got a quick fix in https://github.com/eggheadio/egghead-next/pull/596

Appreciate the PR!
