### ISSUE TITLE
Reserve the primary CTA in the navbar for core business goals of sign up and become a member

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#654]
This is a scoped section of the larger pitch presented here - https://github.com/eggheadio/egghead-next/discussions/637

The primary CTA in our navbar should drive users to the core business goals of signing up for an account and becoming a member.

The navbar should only have one CTA, and it should be the most important action we want a user to take at any time on the site. This action is always going to be related to moving them from anonymous visitor -> paying member.

- Anonymous visitors should see "Get Started" which will take them to the sign up page (currently https://egghead.io/login although we need to change this to an onboarding flow in the future).
- Logged-in non-members should see "Become a Member"
- Logged-in members do not see a CTA in the navbar
- Lapsed members should see "Renew Membership"

![image](https://user-images.githubusercontent.com/5599295/119366581-0851b700-bca9-11eb-91f2-771841612c3a.png)

---

We currently have the "own your online presence" button displayed in the navbar. 
We will need to move this to a banner underneath the navbar (outlined in part 4 of the https://github.com/eggheadio/egghead-next/discussions/637 discussion). That work is outside the scope of this pitch, but related.

I propose we remove the "own your online presence" campaign button for the moment, with the intention of replacing it with the banner as soon as this piece of work is done.

**Comment by joelhooks** [comment]
@MaggieAppleton this looks like a great upgrade!

suggestion: as part of the pitches/issues, can you include what we want to measure for analytics?

concern: dropping our non-membership-related CTAs completely, even if temporarily

I disagree that we should drop the resources being offered there. We are also offering project clubs in addition to the personal brand mini-course. These projects are going well and have only had positive feedback so far.

Great open rates and decent click-throughs!

![image](https://user-images.githubusercontent.com/86834/119414741-fff77d00-bca4-11eb-98e0-9d923fe0787d.png)

My opinion is that the CTA is the CTA and that we don't need to have a secondary banner for this at all. 

The blue button in this design displays the appropriate CTA for the learner at any given time.

Often the blue-button CTA will be "join now!" or some other variant. For members, it might be an active club, or a discount/deal for lapsed members, or an introduction sequence for an anonymous user. We can use high-value "lead magnets" and if there was a concern over annoying learners or other customers we could give it a dismissal option

this is something Brennan teaches where a given customer is going to have a single current offer available based on progressive behavioral profiling and self-selection. It's a very focused personalization, and the way the button is configured right now is a pretty decent start towards implementing what I'm describing on a technical level.

https://github.com/eggheadio/egghead-next/blob/5ef3f6bbef5f7a5d39ae7d1e35d657f05cb7463a/src/components/app/header.tsx#L42-L52

In this `switch` statement we can inspect the customer attributes stored in CK, CIO, egghead, etc which gives us a lot of granular data to present a CTA in this real estate. Rudimentary now, but has a lot of potential coordinating the current offer across channels (email, end-of-video CTAs, end-of-course CTAs, pop-up "toasts", etc)

I like the secondary banner for other transient notifications but would prefer to keep a single CTA in this region of the page if possible with the standout blue button.

**Comment by MaggieAppleton** [comment]
For analytics we can probably keep it simple for now:
1. Overall click rates on each type of button
2. % of clicks -> new account creations
3. % of clicks -> membership purchases

Any others?

I think it's very important the CTA in the navbar stays consistent for two key groups: anonymous visitors and non-membership accounts. Anonymous visitors should always see "get started" (or "sign up" - whatever language we want to use that is directly leading them to account creation). Non-membership accounts should always see "become a member."

Until they're paying members, it's critical people have those always-at-hand, predictable CTAs in the navbar that lead them into our onboarding flow (not much of a flow at the moment - still need to fix up that experience). We never want someone who is on the fence about subscribing to have to go hunting for the 'become a member' button or pricing page when they're finally ready to buy. Without a navbar CTA they would need to track down a pro course, click through the course page, click through to lessons, then click a locked lesson, then click the CTA. 4 vs. 1 click. Every other website our users spend time on has trained them to understand that the large, colourful CTA in the navbar is always where they should click when they're ready to sign up/join/become a member. 

Once they're members we can certainly use that CTA space for other promotions. Agree that the fleeting campaigns (own your online presence / course clubs, etc.) are super valuable and we should still be driving users towards them.
However, if we want to drive any anonymous users or non-member accounts into those kinds of offerings, we'll need to do it through homepage promotions or banners instead of in the navbar CTA.

**Comment by joelhooks** [comment]
The career related lead magnets are a chance to “get started” and actually do something in their interests, not just what we want them to do (give us money)


They also aren’t “fleeting” at all. 


This header design rework is great, but i’m going to continue using that real estate for marketing and “current offer” approach using personalization data and a/b testing for now. 


As other aspects emerge (eg the “get started” button has a target, the sun-banner exists, etc) I’m happy to reconsider and tests alternate locations for conversions to see how they perform relative to other placements. 


Capturing the full analytics funnel will be useful for that analysis.

**Comment by joelhooks** [comment]
Maggie and I chatted about this and the blue button will expand the existing switch that displays a CTA to incorporate the additional states/CTAs `become a member` and `renew membership`

The existing CTAs will remain for now while we iterate.

This should be good to go!
