### ISSUE TITLE
Autoplay button is not centered

### ISSUE THREAD

**Issue by Beraliv** [eggheadio/egghead-next#684]
When I open video player page (e.g. https://egghead.io/lessons/rust-rustlings-iterators2-introducing-iterators-by-manually-calling-next-and-using-iter) I see this autoplay button:

<img width="1328" alt="Screenshot 2021-06-09 at 22 56 20" src="https://user-images.githubusercontent.com/2991847/121428382-660b2200-c97e-11eb-9263-e99ca263530d.png">

Expected behaviour:

* Autoplay button should be centered

Actual behaviour:

* It's on top left instead

**Comment by Beraliv** [comment]
Looks like it's `BigPlayButton` from `cueplayer-react`

**Comment by Beraliv** [comment]
@joelhooks probably wrong place for the issue, should I move it to https://github.com/joelhooks/cueplayer-react/issues?

**Comment by DrShpongle** [comment]
@Beraliv should be fixed now

**Comment by Beraliv** [comment]
Yeah, now it's fixed 💪

Thank you!
