### ISSUE TITLE
Add Browse Flyout Menu to Navbar

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#722]
Our learners routinely report that browsing the site is difficult and they have trouble finding content. This is a larger information architecture problem we need to holistically address in the future. I propose we add a browse flyout menu as one small, tangible step towards improving the browsing experience in the short term.

Our curated homepage approach helps people see what's new and featured, but doesn't help people get a big picture view of all the available content and topics.

We improved this slightly when we added a "browse" button to the navigation bar which links to `/topics`. However, our topics page is a long list of all available topics in alphabetical order. This doesn't direct people to pages where we have the most content (JavaScript, React, etc.) and doesn't make clear all the types of content (articles, podcasts, etc.)

I propose we add a flyout menu to our existing browse button. This will give users quicker, easier access to any topics page no matter where they are on the site.
This feature should:
- Show the flyout menu when learners click on the browse button
- Hide the flyout menu when learners click the browse button when the menu is open. If they click outside the menu anywhere else on the page it should also hide the flyout menu
- Offer a list of 12-15 topic links in order of popularity and content volume. Clicking one of these takes you to the relevant curated topic page. We can base these off stats from Mixpanel on our most clicked topics:
![image](https://user-images.githubusercontent.com/5599295/123085105-cc318380-d419-11eb-9af3-2adcb98fe8ab.png)

- Offer links to our `/podcasts`,  `/talks`, and `/articles` pages at the bottom to help learners discover and quickly access these
- Allow learners to still navigate to the full `/topics` page via a "browse all topics" button.
- Use the Tailwinds CSS flyout menu components as a base: https://tailwindui.com/components/marketing/elements/flyout-menus. We shouldn't need to deviate from these designs much.
- Follow the established behaviour many other educational websites use for this design pattern. Take a look at the browse flyout behaviour on [skillshare](https://www.skillshare.com/home), [masterclass](https://www.masterclass.com/), and [datacamp](https://www.datacamp.com/)
- All links in the menu should be wrapped with a tracking function that logs the location (browse menu) and the topic name (javascript, articles, etc.)
- Menu needs to meet a11y accessibility standards: [How to Create Drop-Down and Fly-Out Menus That Are Web-Accessible](https://blog.hubspot.com/website/accessible-drop-down-menus)

Mockups using the Tailwinds CSS base are available in Figma in the `egghead Design System` file. Look for the `Navigation` page in the left-hand sidebar to find them:

![image](https://user-images.githubusercontent.com/5599295/123083581-14e83d00-d418-11eb-8595-e5d3198c582a.png)

For background context, this was proposed as part of a larger discussion around the navigation bar and CTAs here: https://github.com/eggheadio/egghead-next/discussions/637

Do others think this is a worthwhile use of our developer resources? Are there any technical considerations or design issues I haven't addressed above?

**Comment by joelhooks** [comment]
This looks great, a huge improvement. 

I think analytics and accessibility details would be good to have in the spec explicitly. 

With a list this size would the icons make it harder to parse? That'd be an interesting test.

**Comment by MaggieAppleton** [comment]
Good point about analytics + accessibility. Will edit the above spec to include them.

Given the small size, I think icons on the technology topics would add extra visual noise without adding any extra information, so probably best to leave them out. The icons on articles, podcasts, and talks could also be dropped. However, I like that they draw more attention to those three links and help distinguish them from the longer list above.

**Comment by MaggieAppleton** [comment]
Solved by #753
