### ISSUE TITLE
Set search filter menu to visible by default

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#768]
We have a very useful and powerful filter menu that learners can use to find relevant content on the site. Sadly, many learners don't use it to find relevant content. This is partially due to the fact we hide the filter menu by default.

Standard view for a search term (filter menu is closed):

![image](https://user-images.githubusercontent.com/5599295/125659547-3204f376-8082-4547-a6a0-d230aaf88b60.png)

If we look at our mixpanel data, we can see out of all searches only 10% of learners make use of search filters:

![image](https://user-images.githubusercontent.com/5599295/125659611-9a14512d-70d8-4059-b821-e1c8c5d0ee6f.png)

![image](https://user-images.githubusercontent.com/5599295/125659598-2e6e6389-3e5a-42eb-9769-2901d29e34d9.png)

It's possible learners simply don't need filtering to find what they're looking for.

However, we've gotten feedback from learners that indicate they don't know the filtering functions exist.
Relevant feedback from learners:
- "it'd be lovely if there was a way to filter courses that are free"
- "It's hard the experience to look for courses, ie free courses or "hot" courses"
- "The complete lack of sorting/filtering ability on almost every page makes it feel impossible to find anything."
- "I went looking for something to help me do fast complex webgl in react. But searching is a nightmare"

The simple solution here is to **have the filter menu open by default** when a learner first uses the search bar. The learner can choose to close the filter menu if they feel it's getting in the way, but at least they know it exists so they can use it in the future.

Once a learner closes the filter menu, it should stay closed until they choose to open it again. The state should persist across sessions.

At the moment, the filter menu also **disappears every time a learner selects a tag in the menu**. This can be disorienting as the interface unexpectedly jumps while the page refreshes. It also makes it difficult to quickly select multiple filters. The filter controls disappear the instant you try to select them.

Current behaviour:

![125483784-dec93456-aee2-4c66-911d-f50c80638136](https://user-images.githubusercontent.com/5599295/125660309-50439913-b73c-4ca1-b1bc-329b1fe9fe87.gif)

As a general rule, the learner should be in control of the open/close state of the menu. It shouldn't automatically close without them choosing to close it.

**Comment by MaggieAppleton** [comment]
Additional note: this is a stop-gap solution for the moment.

We're currently exploring the possibility of moving the filters to a left-hand sidebar in the future so that they're always visible. TBD

Having filter menus open on a user's first visit, and keeping them open while a user searches will help people find our filter functionality in the meantime.

**Comment by joelhooks** [comment]
If the filters are going to be open I'd definitely move the bar below the Topic Page Content. Is that the plan?

**Comment by MaggieAppleton** [comment]
We decided not to go ahead with this temporary fix as discussed in #769
