### ISSUE TITLE
No explicit search button

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#772]
We used to have a visible "search" button to execute a search, but I lobbied for its removal in a previous round of design work (#637).
The previous rationale for removing the search button was that we had numerous bright blue buttons in our navbar that all looked equally important: "browse', "search," and our main CTA.

Previous navbar:
![](https://user-images.githubusercontent.com/5599295/126472487-518bb6a1-63ee-40c1-84a6-2fcdc55db288.png)

In order to make the main CTA stand out more, we made "browse" into a secondary style button and removed the explicit "search" button. Users would then execute a search by pressing return on the keyboard.

A learner wrote in pointing out that they were unable to search while using egghead on a television display that only allowed mouse controls.

We then added the ability to perform a search by clicking the microscope icon to the left of the search query. This is still slightly out of line with industry conventions. Many other websites use the search icon as a "search" button, but place it on the right hand side of the search box:

Twitch:
![image](https://user-images.githubusercontent.com/5599295/126472517-b46eaf0c-7300-4faf-9b76-6f11969395f8.png)

YouTube:
![image](https://user-images.githubusercontent.com/5599295/126472564-324f246d-109c-42ac-9851-1e98686a1eab.png)

To make our search bar more accessible and standardised, we should turn the search icon into a square button and align it to the right of the bar:

![image](https://user-images.githubusercontent.com/5599295/126472589-edba977b-3a84-443c-9440-b65177912a8c.png)

When a user hovers over the search button, the background colour should darken two shades. Eg. from `bg-grey-100` to `bg-gray-300`. Dark mode colours should lighten two shades – from `bg-grey-800` to `bg-grey-600`.

![image](https://user-images.githubusercontent.com/5599295/126474515-ae653ca4-853c-487c-9689-33d5c4b3fb26.png)

The user is still able to execute a search by hitting return on the keyboard. This just 
gives them the additional option of clicking a button.

**Comment by DrShpongle** [comment]
It looks 100% reasonable to me

**Comment by joelhooks** [comment]
this looks great to me and i think covers accessibility and use cases for most users

**Comment by DrShpongle** [comment]
closed via https://github.com/eggheadio/egghead-next/pull/777
