### ISSUE TITLE
Team navigation element not always displayed for team owner

### ISSUE THREAD

**Issue by dealingwith** [eggheadio/egghead-next#778]
We have a team owner who never gets the "Team" navigation element when visiting egghead. Ping me for that account info if needed. This might have been specific to their team/account situation, and we're transferring ownership to a different team member (at their request), so this might be transitory--I suggest time-boxing < 60 minutes to looking for anything obvious with the "Team" display logic and if there's nothing there we might have to wait for another account in this state.

**Comment by jbranchaud** [comment]
We did a server-side PR that addressed how this was displaying for admins.

It sounds like beyond that we believe the 'Team' link is working for all account owners. Or at least we'll pause further investigation until we hear of another instance of this.

**Comment by dealingwith** [comment]
Yes 👍
