### ISSUE TITLE
Notes aren't displaying code blocks.

### ISSUE THREAD

**Issue by lsminter** [eggheadio/egghead-next#793]
The notes are not displaying code blocks in the same TimeStamp'ed block that has text in it. 

Here is the raw markdown.
![Screen Shot 2021-08-03 at 2 59 53 PM](https://user-images.githubusercontent.com/26470581/128092488-cd0f2855-f06f-4d72-b87e-b82dea1ba608.png)

Here is what is getting displayed. 
![Screen Shot 2021-08-03 at 2 59 26 PM](https://user-images.githubusercontent.com/26470581/128092612-8f6ad46c-f9f5-47c8-bcd5-af41854b267b.png)

Vojta addressed this issue in [this PR](https://github.com/eggheadio/egghead-next/pull/785) but due to notes causing lessons to crash. It turns out that the linked PR did not cause the crash so the changes that Vojta made needs to be re-implemented.

**Comment by lsminter** [comment]
Issue is fixed int his PR https://github.com/eggheadio/egghead-next/pull/792

**Comment by joelhooks** [comment]
if you add `fixes #ISSUE_NUMBER` to the PR it references and closes the issue automatically!

**Comment by lsminter** [comment]
Ahhh! Ok!
