### ISSUE TITLE
Add sorting to search results

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#805]
There's currently no way to sort search results. This makes it harder for learners to find relevant content. Learners should be able to sort search results by last updated date, highest review score, and most popular.

We should add a 'sort by' dropdown menu in a bar directly above the search results with options for 'most popular,' 'highest rated,' and 'recently updated'. The default sorting value should be 'most popular'.

- **Most popular** equates to # of views on a course or lesson.
- **Highest rated** equates to highest average rating from learner reviews.
- **Recently updated** equates the last time the course was reviewed, updated, or released.

We should also display the number of search results for a given search above the results.

### Mockups

**Search result count on left and 'sort by' dropdown on right:**

![image](https://user-images.githubusercontent.com/5599295/128748144-4fdf8850-627a-48f4-8206-1b5601901045.png)

**Dropdown menu expanded:**
Current sorting selection should have bold text with a small blue checkmark to indicate it's active.
The order of the items in the dropdown menu shouldn't change.

![image](https://user-images.githubusercontent.com/5599295/128748174-9bd01d4a-a4e6-432c-82a2-f9f7112c0ec7.png)

**Sorting dropdown on a curated landing page**
Sorting dropdown appears below curated content and directly above results

![image](https://user-images.githubusercontent.com/5599295/128748831-ec16587b-ce4a-4bc2-858b-059bcec8349a.png)

**Sorting dropdown on mobile**
Place sorting dropdown directly beneath the search bar. Hide the search results number.

![image](https://user-images.githubusercontent.com/5599295/128751302-4573b790-f31e-4369-a776-02ce79d32d9e.png)

---

### Implementation Details

Dropdown menu can be built using Tailwind UI's dropdown component: https://tailwindui.com/components/application-ui/elements/dropdowns

Sorting should be doable with Algolia: https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/

Unsure of the technical hurdles to get sorting to play nicely with filtering. Ideally, if someone has already selected filters (eg. "react" and "lessons"), the sorting feature should only sort results that are lessons tagged React. Changing the 'sort by' option should not reset filters.

Any details or considerations missing here?

**Comment by joelhooks** [comment]
I think people also want to sort by "published" date which we can easily add to the search properties.

Another interesting field to sort on imo is duration. That speaks a bit to the "find something short to watch" and may surface lessons and such.

**Comment by laurosilvacom** [comment]
Additional implementation details to consider: 

We should use [relevant sorting](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/in-depth/relevant-sort/) instead of _hard sorting_. Relevant sorting provides a more user-friendly experience to the learner by not showing results strictly by an attribute. 

Are we considering using the [Sorting widget](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/use-sorting-ui-widget/#sorting-widget) to create the 'sort by' dropdown? See component [story](https://instantsearchjs.netlify.app/stories/?path=/story/sorting-sortby--default).

**Comment by MaggieAppleton** [comment]
> I think people also want to sort by "published" date which we can easily add to the search properties.
> 
> Another interesting field to sort on imo is duration. That speaks a bit to the "find something short to watch" and may surface lessons and such.

Agree these are both valuable additions 👍 

>Are we considering using the Sorting widget to create the 'sort by' dropdown? See component story.

Looks like that's exactly what we want. I was hoping Algolia had a bunch of good plug-n-play functionality for this.

**Comment by MaggieAppleton** [comment]
Completed: https://github.com/eggheadio/egghead-next/pull/870
