### ISSUE TITLE
Add authors and publish dates to /articles landing page

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#808]
Our current articles landing page (located at  `/blog` - a naming inconsistency issue we should resolve in a separate issue) currently only shows the cover image and title of an article.

![image](https://user-images.githubusercontent.com/5599295/128875775-50dc0d33-9ebb-4b51-8e52-9a88983a3a72.png)

To give readers more context about what they're clicking on, and authors more credit for their work we should visibly add:

- Author name + photo
- Publish date stated relative to current date (yesterday, 2 weeks ago).
	- If it's more than a month old then switch to regular dates: March 20th, 2021. If that turns out to be complex to implement then regular dates are fine.
- 1-2 sentence description. Should be a simple one-liner pulled from Sanity.

At the moment the article cards are formatted on the main articles page: https://github.com/eggheadio/egghead-next/blob/main/src/pages/blog/index.tsx

We could consider pulling them out into their own card component **but we do not need to go down the road of designing an ultimate, universal card component here.** That is a lovely, meaty, future goal that will derail us instead of iteratively improving the articles page today.

### Revised individual card layout with author, date, description:

![image](https://user-images.githubusercontent.com/5599295/128881206-30b3f0c5-45a5-40a6-a1f3-a62c383a2db1.png)

**If there's no description available, only display author and publish date**

![image](https://user-images.githubusercontent.com/5599295/128881276-71b5c592-2baa-43b8-8433-d7b1c07a7462.png)

### Whole page mockup
Page layout can stay the same, we're just adding metadata below the title:
![image](https://user-images.githubusercontent.com/5599295/128881149-08a1d38b-87fa-4500-ba7e-f5148c21d8ec.png)

---

⚡️ **Figma files with design mockups: https://www.figma.com/file/cWvKOJ0XyRte8kyP3LvBAT/Talks-Articles-Podcasts?node-id=101%3A764** ⚡️

🙋‍♀️ Feedback welcome. Are there any technical limitations that would block this work, or design considerations I've overlooked?

**Comment by laurosilvacom** [comment]
This makes sense! 

I think @NicollGuarnizo would be a great candidate to work on this. She's doing similar work for Escuela Frontend.

**Comment by NicollGuarnizo** [comment]
Yeah, I'll work on this :)

**Comment by NicollGuarnizo** [comment]
**This is how it's looking so far:** 

![image](https://user-images.githubusercontent.com/43156646/129278819-839d6ccf-e443-409f-a7ce-2498778fbca4.png)

The description has exactly 150 characters. Personally, I think it looks a little bit tight and we could delete the description. If we go down that road this is how it'll look:

1) 
![image](https://user-images.githubusercontent.com/43156646/129279398-2b99d091-03e6-44b2-9108-33aa255a5b6e.png)

2) 
![image](https://user-images.githubusercontent.com/43156646/129279806-0934f483-9744-4acd-8d39-9ffdace14d80.png)

What do you think @MaggieAppleton? You are the expert in UX/UI :sweat_smile:

**Comment by MaggieAppleton** [comment]
Looking good! I just did a quick pass through and adjusted the text alignment, size, and spacing between some of the elements. Pushed it to the working branch: https://github.com/eggheadio/egghead-next/commit/1361b270daa5f0ace945e06287a43e757ed75995

![image](https://user-images.githubusercontent.com/5599295/129578822-1def3a04-78be-4983-af9d-5f95c4144829.png)

I think it's ready to PR in 👍
