### ISSUE TITLE
GraphQL API not pulling in new course lesson

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-next#814]
An instructor added a new lesson to their course, [TypeScript: Tips and Tricks](https://app.egghead.io/playlists/typescript-tips-and-tricks-20c4). 

Specifically: [Create Class Properties using Constructor Assignment](https://app.egghead.io/lessons/javascript-create-class-properties-using-constructor-assignment?pl=typescript-tips-and-tricks-20c4).

But the lesson does not get added to the list on egghead. This might be an `egghead-rails`-sided issue?

What is interesting is if you navigate to the app.egghead.io route for the course, the lesson shows up as expected

![Image 2021-08-11 at 3 47 45 PM](https://user-images.githubusercontent.com/6188161/129093512-4207db6f-1227-4b67-84b2-be012c35cc41.png)

But that same lesson doesn't show up on the graphql API which is how the course object is loaded: 

https://github.com/eggheadio/egghead-next/blob/main/src/pages/courses/%5Bslug%5D/index.tsx#L44-L59

![Image 2021-08-11 at 3 48 27 PM](https://user-images.githubusercontent.com/6188161/129093628-fa396670-2473-4bc3-8cd0-777e04691d86.png)

**Comment by joelhooks** [comment]
lessons/items are set to aggressively cache (90 mins) in graphql API.

this could be adjusted in several ways:

https://github.com/stackshareio/graphql-cache#usage
