### ISSUE TITLE
Implement `@testing-library` for Cypress tests.

### ISSUE THREAD

**Issue by pedroapfilho** [eggheadio/egghead-next#84]
In my experience, it's better to use the `@testing-library/cypress` if you're using the `@testing-library/react` and `@testing-library/dom`. It's easier to understand and removes a lot of boilerplate.

What do you think?

**Comment by andrew-secret** [comment]
Hey I would love to contribute to your platform. Is there anything I can do here? Let me know 🙏

**Comment by joelhooks** [comment]
i'd love to see what this looks like.
